{
 "title": "dash-forum-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Non Heap Used",
   "type": "gauge",
   "description": "Memória non-heap utilizada",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",area=\"nonheap\"})*100 / sum(jvm_memory_max_bytes{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "description": "Memória heap utilizada.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",area=\"heap\"})*100 / sum(jvm_memory_max_bytes{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "Média de uso de CPU",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"app-forum-api\",instance=\"app-forum-api:8080\", job=\"app-forum-api\"}",
     "legendFormat": "Load average [1m]"
    },
    {
     "expr": "system_cpu_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\"}",
     "legendFormat": "CPU core size"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Número de erro 500 no último minuto.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Média de Latência",
   "type": "timeseries",
   "description": "Latência média por minuto",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "Total Requests/Sec",
   "type": "stat",
   "description": "Número de requisições no último minuto",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Taxa de erro dos últimos 5 minutos",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / \nsum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / \nsum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / \nsum(rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", \nuri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Duração máxima de uma requisição",
   "type": "timeseries",
   "description": "Duração máxima de uma requisição.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", status=\"200\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{method}}  {{status}}"
    }
   ]
  },
  {
   "title": "Número de requisições",
   "type": "timeseries",
   "description": "Número de requisições por endpoint no último minuto.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "Duração média das requisições",
   "type": "timeseries",
   "description": "Duração média de requisições no último minuto.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m]) / \nrate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m])",
     "legendFormat": "{{uri}} {{method}}  {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / \nrate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
     "legendFormat": "{{uri}} {{method}}  {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m]) / \nrate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", \njob=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m])",
     "legendFormat": "{{uri}} {{method}}  {{status}}"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta do último minuto",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",\nuri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\",\nuri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}}-{{method}}-{{status}}"
    }
   ]
  },
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "Pool de conexões",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USER LOGGED",
   "type": "stat",
   "description": "Total de usuários logados nos últimos 10 minutos",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[20m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB CONECTION TIMEOUT",
   "type": "stat",
   "description": "Conexões com o database em timeout",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", pool=\"HikariPool-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOGIN ERRORS",
   "type": "stat",
   "description": "Total de erros de login no último minuto",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "timeseries",
   "description": "Estado das conexões do banco de dados",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", pool=\"HikariPool-1\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", pool=\"HikariPool-1\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", pool=\"HikariPool-1\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Warnings e erros logados nos últimos 5 minutos",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"app-forum-api\", instance=\"app-forum-api:8080\", job=\"app-forum-api\", level=\"error\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}